/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a2.old;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Nathan
 */
public class DashProfile extends javax.swing.JFrame {

    /**
     * Creates new form Dash
     */
    public DashProfile() {
        initComponents();
        this.setResizable(false);
        try {UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());} catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException ignored) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        sbTitleButton = new javax.swing.JButton();
        sbHomeButton = new javax.swing.JButton();
        sbSettingsButton = new javax.swing.JButton();
        sbExitButton = new javax.swing.JButton();
        sbProfileButton = new javax.swing.JButton();
        sbMessagesButton = new javax.swing.JButton();
        sbPaymentsButton = new javax.swing.JButton();
        sbTaxCalculator = new javax.swing.JButton();
        pgProfilePanel = new javax.swing.JPanel();
        pgMessagesTitle = new javax.swing.JLabel();
        pgProfileUsernameLabel = new javax.swing.JLabel();
        pgProfileUsernameInput = new javax.swing.JTextField();
        pgProfileFirstNameLabel = new javax.swing.JLabel();
        pgProfileFirstNameInput = new javax.swing.JTextField();
        pgProfileLastNameLabel = new javax.swing.JLabel();
        pgProfileLastNameInput = new javax.swing.JTextField();
        pgProfileDateOfBirthLabel = new javax.swing.JLabel();
        pgProfileDateOfBirthInput = new javax.swing.JTextField();
        pgProfileAddressLabel = new javax.swing.JLabel();
        pgProfileAddressInput = new javax.swing.JTextField();
        pgProfileIRDNumberLabel = new javax.swing.JLabel();
        pgProfileIRDNumberInput = new javax.swing.JTextField();
        pgProfileSalaryLabel = new javax.swing.JLabel();
        pgProfileSalaryInput = new javax.swing.JTextField();
        pgProfileCarRegoLabel = new javax.swing.JLabel();
        pgProfileCarRegoInput = new javax.swing.JTextField();
        pgProfileHomeOwnerLabel = new javax.swing.JLabel();
        pgProfileHomeOwnerInput = new javax.swing.JTextField();
        pgProfileEmailLabel = new javax.swing.JLabel();
        pgProfileEmailInput = new javax.swing.JTextField();
        pgProfilePasswordLabel = new javax.swing.JLabel();
        pgProfilePasswordInput = new javax.swing.JTextField();
        pgProfileUpdateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Awesomest Billing System");
        setBackground(new java.awt.Color(51, 51, 51));

        sideBar.setBackground(new java.awt.Color(51, 51, 51));

        sbTitleButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\tabs-logo-dash2.png")); // NOI18N
        sbTitleButton.setBorderPainted(false);
        sbTitleButton.setContentAreaFilled(false);

        sbHomeButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\Menu-Home.png")); // NOI18N
        sbHomeButton.setBorder(null);
        sbHomeButton.setBorderPainted(false);
        sbHomeButton.setContentAreaFilled(false);
        sbHomeButton.setMaximumSize(new java.awt.Dimension(75, 75));
        sbHomeButton.setMinimumSize(new java.awt.Dimension(75, 75));

        sbSettingsButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\Menu-Settings.png")); // NOI18N
        sbSettingsButton.setBorder(null);
        sbSettingsButton.setBorderPainted(false);
        sbSettingsButton.setContentAreaFilled(false);
        sbSettingsButton.setMaximumSize(new java.awt.Dimension(75, 75));
        sbSettingsButton.setMinimumSize(new java.awt.Dimension(75, 75));

        sbExitButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\Menu-Exit.png")); // NOI18N
        sbExitButton.setBorder(null);
        sbExitButton.setBorderPainted(false);
        sbExitButton.setContentAreaFilled(false);
        sbExitButton.setMaximumSize(new java.awt.Dimension(75, 75));
        sbExitButton.setMinimumSize(new java.awt.Dimension(75, 75));
        sbExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbExitButtonActionPerformed(evt);
            }
        });

        sbProfileButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\OptionPane-Profile.png")); // NOI18N
        sbProfileButton.setBorder(null);
        sbProfileButton.setBorderPainted(false);
        sbProfileButton.setContentAreaFilled(false);

        sbMessagesButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\OptionPane-Messages.png")); // NOI18N
        sbMessagesButton.setBorder(null);
        sbMessagesButton.setBorderPainted(false);
        sbMessagesButton.setContentAreaFilled(false);

        sbPaymentsButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\OptionPane-Payments.png")); // NOI18N
        sbPaymentsButton.setBorder(null);
        sbPaymentsButton.setBorderPainted(false);
        sbPaymentsButton.setContentAreaFilled(false);

        sbTaxCalculator.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\OptionPane-TaxCalculator.png")); // NOI18N
        sbTaxCalculator.setBorder(null);
        sbTaxCalculator.setBorderPainted(false);
        sbTaxCalculator.setContentAreaFilled(false);

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sbProfileButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sbMessagesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sbPaymentsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sbTaxCalculator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sideBarLayout.createSequentialGroup()
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sideBarLayout.createSequentialGroup()
                                .addComponent(sbHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sbSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sbExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sbTitleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sbTitleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sbHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sbSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sbExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sbProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sbMessagesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sbPaymentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sbTaxCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );

        pgProfilePanel.setForeground(new java.awt.Color(246, 247, 251));

        pgMessagesTitle.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        pgMessagesTitle.setForeground(new java.awt.Color(0, 100, 172));
        pgMessagesTitle.setText("Profile");

        pgProfileUsernameLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileUsernameLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileUsernameLabel.setText("Username");

        pgProfileUsernameInput.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileUsernameInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileUsernameInput.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileUsernameInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileUsernameInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileUsernameInput.setOpaque(true);
        pgProfileUsernameInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgProfileFirstNameLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileFirstNameLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileFirstNameLabel.setText("First Name");

        pgProfileFirstNameInput.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileFirstNameInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileFirstNameInput.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileFirstNameInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileFirstNameInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileFirstNameInput.setOpaque(true);
        pgProfileFirstNameInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgProfileLastNameLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileLastNameLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileLastNameLabel.setText("Last Name");

        pgProfileLastNameInput.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileLastNameInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileLastNameInput.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileLastNameInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileLastNameInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileLastNameInput.setOpaque(true);
        pgProfileLastNameInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgProfileDateOfBirthLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileDateOfBirthLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileDateOfBirthLabel.setText("Date of Birth");

        pgProfileDateOfBirthInput.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileDateOfBirthInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileDateOfBirthInput.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileDateOfBirthInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileDateOfBirthInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileDateOfBirthInput.setOpaque(true);
        pgProfileDateOfBirthInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgProfileAddressLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileAddressLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileAddressLabel.setText("Address");

        pgProfileAddressInput.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileAddressInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileAddressInput.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileAddressInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileAddressInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileAddressInput.setOpaque(true);
        pgProfileAddressInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgProfileIRDNumberLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileIRDNumberLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileIRDNumberLabel.setText("IRD Number");

        pgProfileIRDNumberInput.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileIRDNumberInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileIRDNumberInput.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileIRDNumberInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileIRDNumberInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileIRDNumberInput.setOpaque(true);
        pgProfileIRDNumberInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgProfileSalaryLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileSalaryLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileSalaryLabel.setText("Salary");

        pgProfileSalaryInput.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileSalaryInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileSalaryInput.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileSalaryInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileSalaryInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileSalaryInput.setOpaque(true);
        pgProfileSalaryInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgProfileCarRegoLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileCarRegoLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileCarRegoLabel.setText("Car Registration");

        pgProfileCarRegoInput.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileCarRegoInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileCarRegoInput.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileCarRegoInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileCarRegoInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileCarRegoInput.setOpaque(true);
        pgProfileCarRegoInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgProfileHomeOwnerLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileHomeOwnerLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileHomeOwnerLabel.setText("Home Owner?");

        pgProfileHomeOwnerInput.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileHomeOwnerInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileHomeOwnerInput.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileHomeOwnerInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileHomeOwnerInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileHomeOwnerInput.setOpaque(true);
        pgProfileHomeOwnerInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgProfileEmailLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileEmailLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileEmailLabel.setText("Email");

        pgProfileEmailInput.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileEmailInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileEmailInput.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileEmailInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileEmailInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileEmailInput.setOpaque(true);
        pgProfileEmailInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgProfilePasswordLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfilePasswordLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgProfilePasswordLabel.setText("Password");

        pgProfilePasswordInput.setBackground(new java.awt.Color(204, 204, 204));
        pgProfilePasswordInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfilePasswordInput.setForeground(new java.awt.Color(102, 102, 102));
        pgProfilePasswordInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfilePasswordInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfilePasswordInput.setOpaque(true);
        pgProfilePasswordInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgProfileUpdateButton.setBackground(new java.awt.Color(0, 100, 172));
        pgProfileUpdateButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        pgProfileUpdateButton.setForeground(new java.awt.Color(204, 204, 204));
        pgProfileUpdateButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\ProfilePane-UpdateButton.png")); // NOI18N
        pgProfileUpdateButton.setBorder(null);
        pgProfileUpdateButton.setBorderPainted(false);
        pgProfileUpdateButton.setContentAreaFilled(false);
        pgProfileUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgProfileUpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pgProfilePanelLayout = new javax.swing.GroupLayout(pgProfilePanel);
        pgProfilePanel.setLayout(pgProfilePanelLayout);
        pgProfilePanelLayout.setHorizontalGroup(
            pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgProfilePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pgMessagesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pgProfilePanelLayout.createSequentialGroup()
                        .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pgProfileUpdateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pgProfilePanelLayout.createSequentialGroup()
                                .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pgProfileAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pgProfilePanelLayout.createSequentialGroup()
                                        .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pgProfileCarRegoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pgProfileCarRegoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 48, Short.MAX_VALUE)
                                        .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pgProfileHomeOwnerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                            .addComponent(pgProfileHomeOwnerInput)))
                                    .addGroup(pgProfilePanelLayout.createSequentialGroup()
                                        .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(pgProfileUsernameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                            .addComponent(pgProfileUsernameInput, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(46, 46, 46)
                                        .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(pgProfileFirstNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pgProfileFirstNameInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(pgProfileAddressInput))
                                .addGap(47, 47, 47)
                                .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(pgProfileLastNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pgProfileLastNameInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(pgProfileIRDNumberLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pgProfileIRDNumberInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pgProfileEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pgProfileEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pgProfileSalaryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pgProfileSalaryInput, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(pgProfileDateOfBirthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pgProfileDateOfBirthInput, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(pgProfilePasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(pgProfilePasswordInput))))
                        .addGap(24, 24, 24)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pgProfilePanelLayout.setVerticalGroup(
            pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgProfilePanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(pgMessagesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pgProfilePanelLayout.createSequentialGroup()
                            .addComponent(pgProfileUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pgProfileUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pgProfilePanelLayout.createSequentialGroup()
                            .addComponent(pgProfileFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pgProfileFirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pgProfilePanelLayout.createSequentialGroup()
                            .addComponent(pgProfileLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pgProfileLastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pgProfilePanelLayout.createSequentialGroup()
                        .addComponent(pgProfileDateOfBirthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pgProfileDateOfBirthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pgProfilePanelLayout.createSequentialGroup()
                            .addComponent(pgProfileAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pgProfileAddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pgProfilePanelLayout.createSequentialGroup()
                            .addComponent(pgProfileIRDNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pgProfileIRDNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pgProfilePanelLayout.createSequentialGroup()
                        .addComponent(pgProfileSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pgProfileSalaryInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pgProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pgProfilePanelLayout.createSequentialGroup()
                            .addComponent(pgProfileCarRegoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pgProfileCarRegoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pgProfilePanelLayout.createSequentialGroup()
                            .addComponent(pgProfileHomeOwnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pgProfileHomeOwnerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pgProfilePanelLayout.createSequentialGroup()
                        .addComponent(pgProfileEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pgProfileEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pgProfilePanelLayout.createSequentialGroup()
                        .addComponent(pgProfilePasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pgProfilePasswordInput)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pgProfileUpdateButton)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pgProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sbExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sbExitButtonActionPerformed

    private void pgProfileUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgProfileUpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgProfileUpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pgMessagesTitle;
    private javax.swing.JTextField pgProfileAddressInput;
    private javax.swing.JLabel pgProfileAddressLabel;
    private javax.swing.JTextField pgProfileCarRegoInput;
    private javax.swing.JLabel pgProfileCarRegoLabel;
    private javax.swing.JTextField pgProfileDateOfBirthInput;
    private javax.swing.JLabel pgProfileDateOfBirthLabel;
    private javax.swing.JTextField pgProfileEmailInput;
    private javax.swing.JLabel pgProfileEmailLabel;
    private javax.swing.JTextField pgProfileFirstNameInput;
    private javax.swing.JLabel pgProfileFirstNameLabel;
    private javax.swing.JTextField pgProfileHomeOwnerInput;
    private javax.swing.JLabel pgProfileHomeOwnerLabel;
    private javax.swing.JTextField pgProfileIRDNumberInput;
    private javax.swing.JLabel pgProfileIRDNumberLabel;
    private javax.swing.JTextField pgProfileLastNameInput;
    private javax.swing.JLabel pgProfileLastNameLabel;
    private javax.swing.JPanel pgProfilePanel;
    private javax.swing.JTextField pgProfilePasswordInput;
    private javax.swing.JLabel pgProfilePasswordLabel;
    private javax.swing.JTextField pgProfileSalaryInput;
    private javax.swing.JLabel pgProfileSalaryLabel;
    private javax.swing.JButton pgProfileUpdateButton;
    private javax.swing.JTextField pgProfileUsernameInput;
    private javax.swing.JLabel pgProfileUsernameLabel;
    private javax.swing.JButton sbExitButton;
    private javax.swing.JButton sbHomeButton;
    private javax.swing.JButton sbMessagesButton;
    private javax.swing.JButton sbPaymentsButton;
    private javax.swing.JButton sbProfileButton;
    private javax.swing.JButton sbSettingsButton;
    private javax.swing.JButton sbTaxCalculator;
    private javax.swing.JButton sbTitleButton;
    private javax.swing.JPanel sideBar;
    // End of variables declaration//GEN-END:variables
}
