/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a2.old;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Nathan
 */
public class DashTaxCalculator extends javax.swing.JFrame {

    /**
     * Creates new form Dash
     */
    public DashTaxCalculator() {
        initComponents();
        this.setResizable(false);
        try {UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());} catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException ignored) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        sbTitleButton = new javax.swing.JButton();
        sbHomeButton = new javax.swing.JButton();
        sbSettingsButton = new javax.swing.JButton();
        sbExitButton = new javax.swing.JButton();
        sbProfileButton = new javax.swing.JButton();
        sbMessagesButton = new javax.swing.JButton();
        sbPaymentsButton = new javax.swing.JButton();
        sbTaxCalculator = new javax.swing.JButton();
        pgTaxCalculatorPanel = new javax.swing.JPanel();
        pgMessagesTitle = new javax.swing.JLabel();
        pgProfileUsernameLabel = new javax.swing.JLabel();
        pgProfileUsernameInput = new javax.swing.JTextField();
        pgProfileCarRegoLabel = new javax.swing.JLabel();
        pgProfileCarRegoInput = new javax.swing.JTextField();
        pgProfileCarRegoInput1 = new javax.swing.JTextField();
        pgProfileCarRegoLabel1 = new javax.swing.JLabel();
        pgProfileCarRegoInput2 = new javax.swing.JTextField();
        pgProfileCarRegoLabel2 = new javax.swing.JLabel();
        pgProfileCarRegoInput3 = new javax.swing.JTextField();
        pgProfileCarRegoLabel3 = new javax.swing.JLabel();
        pgProfileCarRegoInput4 = new javax.swing.JTextField();
        pgProfileCarRegoLabel4 = new javax.swing.JLabel();
        pgProfileUsernameInput1 = new javax.swing.JTextField();
        pgProfileUsernameLabel1 = new javax.swing.JLabel();
        pgProfileUsernameLabel2 = new javax.swing.JLabel();
        pgProfileUsernameInput2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Awesomest Billing System");
        setBackground(new java.awt.Color(51, 51, 51));

        sideBar.setBackground(new java.awt.Color(51, 51, 51));

        sbTitleButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\tabs-logo-dash2.png")); // NOI18N
        sbTitleButton.setBorderPainted(false);
        sbTitleButton.setContentAreaFilled(false);

        sbHomeButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\Menu-Home.png")); // NOI18N
        sbHomeButton.setBorder(null);
        sbHomeButton.setBorderPainted(false);
        sbHomeButton.setContentAreaFilled(false);
        sbHomeButton.setMaximumSize(new java.awt.Dimension(75, 75));
        sbHomeButton.setMinimumSize(new java.awt.Dimension(75, 75));

        sbSettingsButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\Menu-Settings.png")); // NOI18N
        sbSettingsButton.setBorder(null);
        sbSettingsButton.setBorderPainted(false);
        sbSettingsButton.setContentAreaFilled(false);
        sbSettingsButton.setMaximumSize(new java.awt.Dimension(75, 75));
        sbSettingsButton.setMinimumSize(new java.awt.Dimension(75, 75));

        sbExitButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\Menu-Exit.png")); // NOI18N
        sbExitButton.setBorder(null);
        sbExitButton.setBorderPainted(false);
        sbExitButton.setContentAreaFilled(false);
        sbExitButton.setMaximumSize(new java.awt.Dimension(75, 75));
        sbExitButton.setMinimumSize(new java.awt.Dimension(75, 75));
        sbExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbExitButtonActionPerformed(evt);
            }
        });

        sbProfileButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\OptionPane-Profile.png")); // NOI18N
        sbProfileButton.setBorder(null);
        sbProfileButton.setBorderPainted(false);
        sbProfileButton.setContentAreaFilled(false);

        sbMessagesButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\OptionPane-Messages.png")); // NOI18N
        sbMessagesButton.setBorder(null);
        sbMessagesButton.setBorderPainted(false);
        sbMessagesButton.setContentAreaFilled(false);

        sbPaymentsButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\OptionPane-Payments.png")); // NOI18N
        sbPaymentsButton.setBorder(null);
        sbPaymentsButton.setBorderPainted(false);
        sbPaymentsButton.setContentAreaFilled(false);

        sbTaxCalculator.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\OptionPane-TaxCalculator.png")); // NOI18N
        sbTaxCalculator.setBorder(null);
        sbTaxCalculator.setBorderPainted(false);
        sbTaxCalculator.setContentAreaFilled(false);

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sbProfileButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sbMessagesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sbPaymentsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sbTaxCalculator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sideBarLayout.createSequentialGroup()
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sideBarLayout.createSequentialGroup()
                                .addComponent(sbHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sbSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sbExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sbTitleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sbTitleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sbHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sbSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sbExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sbProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sbMessagesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sbPaymentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sbTaxCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );

        pgTaxCalculatorPanel.setForeground(new java.awt.Color(246, 247, 251));

        pgMessagesTitle.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        pgMessagesTitle.setForeground(new java.awt.Color(0, 100, 172));
        pgMessagesTitle.setText("Tax Calculator");

        pgProfileUsernameLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileUsernameLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileUsernameLabel.setText("Salary To Check");

        pgProfileUsernameInput.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileUsernameInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileUsernameInput.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileUsernameInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileUsernameInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileUsernameInput.setOpaque(true);
        pgProfileUsernameInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgProfileCarRegoLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileCarRegoLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileCarRegoLabel.setText("10.5%");

        pgProfileCarRegoInput.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileCarRegoInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileCarRegoInput.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileCarRegoInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileCarRegoInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileCarRegoInput.setOpaque(true);
        pgProfileCarRegoInput.setSelectionColor(new java.awt.Color(252, 189, 27));
        pgProfileCarRegoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgProfileCarRegoInputActionPerformed(evt);
            }
        });

        pgProfileCarRegoInput1.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileCarRegoInput1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileCarRegoInput1.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileCarRegoInput1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileCarRegoInput1.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileCarRegoInput1.setOpaque(true);
        pgProfileCarRegoInput1.setSelectionColor(new java.awt.Color(252, 189, 27));
        pgProfileCarRegoInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgProfileCarRegoInput1ActionPerformed(evt);
            }
        });

        pgProfileCarRegoLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileCarRegoLabel1.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileCarRegoLabel1.setText("17.5%");

        pgProfileCarRegoInput2.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileCarRegoInput2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileCarRegoInput2.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileCarRegoInput2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileCarRegoInput2.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileCarRegoInput2.setOpaque(true);
        pgProfileCarRegoInput2.setSelectionColor(new java.awt.Color(252, 189, 27));
        pgProfileCarRegoInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgProfileCarRegoInput2ActionPerformed(evt);
            }
        });

        pgProfileCarRegoLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileCarRegoLabel2.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileCarRegoLabel2.setText("30%");

        pgProfileCarRegoInput3.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileCarRegoInput3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileCarRegoInput3.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileCarRegoInput3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileCarRegoInput3.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileCarRegoInput3.setOpaque(true);
        pgProfileCarRegoInput3.setSelectionColor(new java.awt.Color(252, 189, 27));
        pgProfileCarRegoInput3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgProfileCarRegoInput3ActionPerformed(evt);
            }
        });

        pgProfileCarRegoLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileCarRegoLabel3.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileCarRegoLabel3.setText("33%");

        pgProfileCarRegoInput4.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileCarRegoInput4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileCarRegoInput4.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileCarRegoInput4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileCarRegoInput4.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileCarRegoInput4.setOpaque(true);
        pgProfileCarRegoInput4.setSelectionColor(new java.awt.Color(252, 189, 27));
        pgProfileCarRegoInput4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgProfileCarRegoInput4ActionPerformed(evt);
            }
        });

        pgProfileCarRegoLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileCarRegoLabel4.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileCarRegoLabel4.setText("39%");

        pgProfileUsernameInput1.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileUsernameInput1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileUsernameInput1.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileUsernameInput1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileUsernameInput1.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileUsernameInput1.setOpaque(true);
        pgProfileUsernameInput1.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgProfileUsernameLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileUsernameLabel1.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileUsernameLabel1.setText("Total Taxed Amount");

        pgProfileUsernameLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgProfileUsernameLabel2.setForeground(new java.awt.Color(153, 153, 153));
        pgProfileUsernameLabel2.setText("Effective Tax Rate");

        pgProfileUsernameInput2.setBackground(new java.awt.Color(204, 204, 204));
        pgProfileUsernameInput2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgProfileUsernameInput2.setForeground(new java.awt.Color(102, 102, 102));
        pgProfileUsernameInput2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgProfileUsernameInput2.setCaretColor(new java.awt.Color(102, 102, 102));
        pgProfileUsernameInput2.setOpaque(true);
        pgProfileUsernameInput2.setSelectionColor(new java.awt.Color(252, 189, 27));
        pgProfileUsernameInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgProfileUsernameInput2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\TaxCalculatorPane-CalculateButton.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pgTaxCalculatorPanelLayout = new javax.swing.GroupLayout(pgTaxCalculatorPanel);
        pgTaxCalculatorPanel.setLayout(pgTaxCalculatorPanelLayout);
        pgTaxCalculatorPanelLayout.setHorizontalGroup(
            pgTaxCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgTaxCalculatorPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pgTaxCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgMessagesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pgProfileUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pgTaxCalculatorPanelLayout.createSequentialGroup()
                        .addGroup(pgTaxCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pgProfileUsernameLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pgProfileUsernameInput1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pgTaxCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pgProfileUsernameLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pgProfileUsernameInput2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pgTaxCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pgTaxCalculatorPanelLayout.createSequentialGroup()
                            .addComponent(pgProfileUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pgTaxCalculatorPanelLayout.createSequentialGroup()
                            .addGroup(pgTaxCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pgProfileCarRegoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pgProfileCarRegoInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(pgTaxCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pgProfileCarRegoLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pgProfileCarRegoInput1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(pgTaxCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pgProfileCarRegoLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pgProfileCarRegoInput2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(pgTaxCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pgProfileCarRegoLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pgProfileCarRegoInput3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(pgTaxCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pgProfileCarRegoLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pgProfileCarRegoInput4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pgTaxCalculatorPanelLayout.setVerticalGroup(
            pgTaxCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgTaxCalculatorPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(pgMessagesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgProfileUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pgTaxCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pgProfileUsernameInput))
                .addGroup(pgTaxCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pgTaxCalculatorPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pgTaxCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pgTaxCalculatorPanelLayout.createSequentialGroup()
                                .addComponent(pgProfileCarRegoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pgProfileCarRegoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pgTaxCalculatorPanelLayout.createSequentialGroup()
                                .addComponent(pgProfileCarRegoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pgProfileCarRegoInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pgTaxCalculatorPanelLayout.createSequentialGroup()
                                .addComponent(pgProfileCarRegoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pgProfileCarRegoInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pgTaxCalculatorPanelLayout.createSequentialGroup()
                                .addComponent(pgProfileCarRegoLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pgProfileCarRegoInput4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pgTaxCalculatorPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(pgProfileCarRegoLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pgProfileCarRegoInput3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pgProfileUsernameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pgProfileUsernameInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pgTaxCalculatorPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pgProfileUsernameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pgProfileUsernameInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgTaxCalculatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pgTaxCalculatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sbExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sbExitButtonActionPerformed

    private void pgProfileCarRegoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgProfileCarRegoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgProfileCarRegoInputActionPerformed

    private void pgProfileCarRegoInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgProfileCarRegoInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgProfileCarRegoInput1ActionPerformed

    private void pgProfileCarRegoInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgProfileCarRegoInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgProfileCarRegoInput2ActionPerformed

    private void pgProfileCarRegoInput3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgProfileCarRegoInput3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgProfileCarRegoInput3ActionPerformed

    private void pgProfileCarRegoInput4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgProfileCarRegoInput4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgProfileCarRegoInput4ActionPerformed

    private void pgProfileUsernameInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgProfileUsernameInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgProfileUsernameInput2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashTaxCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashTaxCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashTaxCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashTaxCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashTaxCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel pgMessagesTitle;
    private javax.swing.JTextField pgProfileCarRegoInput;
    private javax.swing.JTextField pgProfileCarRegoInput1;
    private javax.swing.JTextField pgProfileCarRegoInput2;
    private javax.swing.JTextField pgProfileCarRegoInput3;
    private javax.swing.JTextField pgProfileCarRegoInput4;
    private javax.swing.JLabel pgProfileCarRegoLabel;
    private javax.swing.JLabel pgProfileCarRegoLabel1;
    private javax.swing.JLabel pgProfileCarRegoLabel2;
    private javax.swing.JLabel pgProfileCarRegoLabel3;
    private javax.swing.JLabel pgProfileCarRegoLabel4;
    private javax.swing.JTextField pgProfileUsernameInput;
    private javax.swing.JTextField pgProfileUsernameInput1;
    private javax.swing.JTextField pgProfileUsernameInput2;
    private javax.swing.JLabel pgProfileUsernameLabel;
    private javax.swing.JLabel pgProfileUsernameLabel1;
    private javax.swing.JLabel pgProfileUsernameLabel2;
    private javax.swing.JPanel pgTaxCalculatorPanel;
    private javax.swing.JButton sbExitButton;
    private javax.swing.JButton sbHomeButton;
    private javax.swing.JButton sbMessagesButton;
    private javax.swing.JButton sbPaymentsButton;
    private javax.swing.JButton sbProfileButton;
    private javax.swing.JButton sbSettingsButton;
    private javax.swing.JButton sbTaxCalculator;
    private javax.swing.JButton sbTitleButton;
    private javax.swing.JPanel sideBar;
    // End of variables declaration//GEN-END:variables
}
