/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a2.old;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Nathan
 */
public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form Dash
     */
    public RegisterPage() {
        initComponents();
        this.setResizable(false);
//        try {UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());} catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException ignored) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgRegisterPanel = new javax.swing.JPanel();
        pgRegisterUsernameLabel = new javax.swing.JLabel();
        pgRegisterUsernameInput = new javax.swing.JTextField();
        pgRegisterFirstNameLabel = new javax.swing.JLabel();
        pgRegisterFirstNameInput = new javax.swing.JTextField();
        pgRegisterLastNameLabel = new javax.swing.JLabel();
        pgRegisterLastNameInput = new javax.swing.JTextField();
        pgRegisterDateOfBirthLabel = new javax.swing.JLabel();
        pgRegisterDateOfBirthInput = new javax.swing.JTextField();
        pgRegisterAddressLabel = new javax.swing.JLabel();
        pgRegisterAddressInput = new javax.swing.JTextField();
        pgRegisterIRDNumberLabel = new javax.swing.JLabel();
        pgRegisterIRDNumberInput = new javax.swing.JTextField();
        pgRegisterSalaryLabel = new javax.swing.JLabel();
        pgRegisterSalaryInput = new javax.swing.JTextField();
        pgRegisterCarRegoLabel = new javax.swing.JLabel();
        pgRegisterCarRegoInput = new javax.swing.JTextField();
        pgRegisterHomeOwnerLabel = new javax.swing.JLabel();
        pgRegisterHomeOwnerCombo = new javax.swing.JComboBox<>();
        pgRegisterEmailLabel = new javax.swing.JLabel();
        pgRegisterEmailInput = new javax.swing.JTextField();
        pgRegisterPasswordLabel = new javax.swing.JLabel();
        pgRegisterPasswordInput = new javax.swing.JTextField();
        pgRegisterUpdateButton = new javax.swing.JButton();
        pgRegisterLogoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Awesomest Billing System");
        setBackground(new java.awt.Color(51, 51, 51));

        pgRegisterPanel.setForeground(new java.awt.Color(246, 247, 251));

        pgRegisterUsernameLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgRegisterUsernameLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgRegisterUsernameLabel.setText("Username");

        pgRegisterUsernameInput.setBackground(new java.awt.Color(204, 204, 204));
        pgRegisterUsernameInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgRegisterUsernameInput.setForeground(new java.awt.Color(102, 102, 102));
        pgRegisterUsernameInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgRegisterUsernameInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgRegisterUsernameInput.setOpaque(true);
        pgRegisterUsernameInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgRegisterFirstNameLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgRegisterFirstNameLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgRegisterFirstNameLabel.setText("First Name");

        pgRegisterFirstNameInput.setBackground(new java.awt.Color(204, 204, 204));
        pgRegisterFirstNameInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgRegisterFirstNameInput.setForeground(new java.awt.Color(102, 102, 102));
        pgRegisterFirstNameInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgRegisterFirstNameInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgRegisterFirstNameInput.setOpaque(true);
        pgRegisterFirstNameInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgRegisterLastNameLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgRegisterLastNameLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgRegisterLastNameLabel.setText("Last Name");

        pgRegisterLastNameInput.setBackground(new java.awt.Color(204, 204, 204));
        pgRegisterLastNameInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgRegisterLastNameInput.setForeground(new java.awt.Color(102, 102, 102));
        pgRegisterLastNameInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgRegisterLastNameInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgRegisterLastNameInput.setOpaque(true);
        pgRegisterLastNameInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgRegisterDateOfBirthLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgRegisterDateOfBirthLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgRegisterDateOfBirthLabel.setText("Date of Birth");

        pgRegisterDateOfBirthInput.setBackground(new java.awt.Color(204, 204, 204));
        pgRegisterDateOfBirthInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgRegisterDateOfBirthInput.setForeground(new java.awt.Color(102, 102, 102));
        pgRegisterDateOfBirthInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgRegisterDateOfBirthInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgRegisterDateOfBirthInput.setOpaque(true);
        pgRegisterDateOfBirthInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgRegisterAddressLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgRegisterAddressLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgRegisterAddressLabel.setText("Address");

        pgRegisterAddressInput.setBackground(new java.awt.Color(204, 204, 204));
        pgRegisterAddressInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgRegisterAddressInput.setForeground(new java.awt.Color(102, 102, 102));
        pgRegisterAddressInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgRegisterAddressInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgRegisterAddressInput.setOpaque(true);
        pgRegisterAddressInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgRegisterIRDNumberLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgRegisterIRDNumberLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgRegisterIRDNumberLabel.setText("IRD Number");

        pgRegisterIRDNumberInput.setBackground(new java.awt.Color(204, 204, 204));
        pgRegisterIRDNumberInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgRegisterIRDNumberInput.setForeground(new java.awt.Color(102, 102, 102));
        pgRegisterIRDNumberInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgRegisterIRDNumberInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgRegisterIRDNumberInput.setOpaque(true);
        pgRegisterIRDNumberInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgRegisterSalaryLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgRegisterSalaryLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgRegisterSalaryLabel.setText("Salary");

        pgRegisterSalaryInput.setBackground(new java.awt.Color(204, 204, 204));
        pgRegisterSalaryInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgRegisterSalaryInput.setForeground(new java.awt.Color(102, 102, 102));
        pgRegisterSalaryInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgRegisterSalaryInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgRegisterSalaryInput.setOpaque(true);
        pgRegisterSalaryInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgRegisterCarRegoLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgRegisterCarRegoLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgRegisterCarRegoLabel.setText("Car Registration");

        pgRegisterCarRegoInput.setBackground(new java.awt.Color(204, 204, 204));
        pgRegisterCarRegoInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgRegisterCarRegoInput.setForeground(new java.awt.Color(102, 102, 102));
        pgRegisterCarRegoInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgRegisterCarRegoInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgRegisterCarRegoInput.setOpaque(true);
        pgRegisterCarRegoInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgRegisterHomeOwnerLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgRegisterHomeOwnerLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgRegisterHomeOwnerLabel.setText("Home Owner?");

        pgRegisterHomeOwnerCombo.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgRegisterHomeOwnerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        pgRegisterHomeOwnerCombo.setBorder(null);

        pgRegisterEmailLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgRegisterEmailLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgRegisterEmailLabel.setText("Email");

        pgRegisterEmailInput.setBackground(new java.awt.Color(204, 204, 204));
        pgRegisterEmailInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgRegisterEmailInput.setForeground(new java.awt.Color(102, 102, 102));
        pgRegisterEmailInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgRegisterEmailInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgRegisterEmailInput.setOpaque(true);
        pgRegisterEmailInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgRegisterPasswordLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgRegisterPasswordLabel.setForeground(new java.awt.Color(153, 153, 153));
        pgRegisterPasswordLabel.setText("Password");

        pgRegisterPasswordInput.setBackground(new java.awt.Color(204, 204, 204));
        pgRegisterPasswordInput.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgRegisterPasswordInput.setForeground(new java.awt.Color(102, 102, 102));
        pgRegisterPasswordInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgRegisterPasswordInput.setCaretColor(new java.awt.Color(102, 102, 102));
        pgRegisterPasswordInput.setOpaque(true);
        pgRegisterPasswordInput.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgRegisterUpdateButton.setBackground(new java.awt.Color(0, 100, 172));
        pgRegisterUpdateButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        pgRegisterUpdateButton.setForeground(new java.awt.Color(204, 204, 204));
        pgRegisterUpdateButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\RegisterPage-Submit.png")); // NOI18N
        pgRegisterUpdateButton.setBorder(null);
        pgRegisterUpdateButton.setBorderPainted(false);
        pgRegisterUpdateButton.setContentAreaFilled(false);
        pgRegisterUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgRegisterUpdateButtonActionPerformed(evt);
            }
        });

        pgRegisterLogoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\RegisterPage-Logo.png")); // NOI18N

        javax.swing.GroupLayout pgRegisterPanelLayout = new javax.swing.GroupLayout(pgRegisterPanel);
        pgRegisterPanel.setLayout(pgRegisterPanelLayout);
        pgRegisterPanelLayout.setHorizontalGroup(
            pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pgRegisterUpdateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                                .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pgRegisterAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                                        .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pgRegisterCarRegoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pgRegisterCarRegoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pgRegisterHomeOwnerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                            .addComponent(pgRegisterHomeOwnerCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                                        .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(pgRegisterUsernameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pgRegisterUsernameInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(46, 46, 46)
                                        .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(pgRegisterFirstNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pgRegisterFirstNameInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(pgRegisterAddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pgRegisterLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pgRegisterLastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pgRegisterIRDNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pgRegisterIRDNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pgRegisterEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pgRegisterEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pgRegisterSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pgRegisterSalaryInput, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pgRegisterDateOfBirthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pgRegisterDateOfBirthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pgRegisterPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pgRegisterPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(pgRegisterLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pgRegisterPanelLayout.setVerticalGroup(
            pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pgRegisterLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                            .addComponent(pgRegisterUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pgRegisterUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                            .addComponent(pgRegisterFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pgRegisterFirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pgRegisterPanelLayout.createSequentialGroup()
                            .addComponent(pgRegisterLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pgRegisterLastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                        .addComponent(pgRegisterDateOfBirthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pgRegisterDateOfBirthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                            .addComponent(pgRegisterAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pgRegisterAddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                            .addComponent(pgRegisterIRDNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pgRegisterIRDNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                        .addComponent(pgRegisterSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pgRegisterSalaryInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                        .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pgRegisterPanelLayout.createSequentialGroup()
                                .addComponent(pgRegisterCarRegoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pgRegisterPanelLayout.createSequentialGroup()
                                .addComponent(pgRegisterHomeOwnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(pgRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pgRegisterCarRegoInput, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(pgRegisterHomeOwnerCombo)))
                    .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                        .addComponent(pgRegisterEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pgRegisterEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pgRegisterPanelLayout.createSequentialGroup()
                        .addComponent(pgRegisterPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pgRegisterPasswordInput)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(pgRegisterUpdateButton)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pgRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pgRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pgRegisterUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgRegisterUpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgRegisterUpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField pgRegisterAddressInput;
    private javax.swing.JLabel pgRegisterAddressLabel;
    private javax.swing.JTextField pgRegisterCarRegoInput;
    private javax.swing.JLabel pgRegisterCarRegoLabel;
    private javax.swing.JTextField pgRegisterDateOfBirthInput;
    private javax.swing.JLabel pgRegisterDateOfBirthLabel;
    private javax.swing.JTextField pgRegisterEmailInput;
    private javax.swing.JLabel pgRegisterEmailLabel;
    private javax.swing.JTextField pgRegisterFirstNameInput;
    private javax.swing.JLabel pgRegisterFirstNameLabel;
    private javax.swing.JComboBox<String> pgRegisterHomeOwnerCombo;
    private javax.swing.JLabel pgRegisterHomeOwnerLabel;
    private javax.swing.JTextField pgRegisterIRDNumberInput;
    private javax.swing.JLabel pgRegisterIRDNumberLabel;
    private javax.swing.JTextField pgRegisterLastNameInput;
    private javax.swing.JLabel pgRegisterLastNameLabel;
    private javax.swing.JLabel pgRegisterLogoLabel;
    private javax.swing.JPanel pgRegisterPanel;
    private javax.swing.JTextField pgRegisterPasswordInput;
    private javax.swing.JLabel pgRegisterPasswordLabel;
    private javax.swing.JTextField pgRegisterSalaryInput;
    private javax.swing.JLabel pgRegisterSalaryLabel;
    private javax.swing.JButton pgRegisterUpdateButton;
    private javax.swing.JTextField pgRegisterUsernameInput;
    private javax.swing.JLabel pgRegisterUsernameLabel;
    // End of variables declaration//GEN-END:variables
}
