/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a2.old;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Nathan
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form Dash
     */
    public StartPage() {
        initComponents();
        this.setResizable(false);
//        try {UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());} catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException ignored) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgMainPanel = new javax.swing.JPanel();
        pgMainTitleLogo = new javax.swing.JLabel();
        pgMainFiller = new javax.swing.JTextField();
        pgMainLoginButton = new javax.swing.JButton();
        pgMainRegisterButton = new javax.swing.JButton();
        pgMainExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Awesomest Billing System");
        setBackground(new java.awt.Color(51, 51, 51));

        pgMainPanel.setForeground(new java.awt.Color(246, 247, 251));

        pgMainTitleLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\StartupPage-Logo.png")); // NOI18N

        pgMainFiller.setEditable(false);
        pgMainFiller.setBackground(new java.awt.Color(204, 204, 204));
        pgMainFiller.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgMainFiller.setForeground(new java.awt.Color(102, 102, 102));
        pgMainFiller.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgMainFiller.setCaretColor(new java.awt.Color(102, 102, 102));
        pgMainFiller.setOpaque(true);
        pgMainFiller.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgMainLoginButton.setBackground(new java.awt.Color(0, 100, 172));
        pgMainLoginButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        pgMainLoginButton.setForeground(new java.awt.Color(204, 204, 204));
        pgMainLoginButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\StartupPage-Login.png")); // NOI18N
        pgMainLoginButton.setBorder(null);
        pgMainLoginButton.setBorderPainted(false);
        pgMainLoginButton.setContentAreaFilled(false);
        pgMainLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgMainLoginButtonActionPerformed(evt);
            }
        });

        pgMainRegisterButton.setBackground(new java.awt.Color(0, 100, 172));
        pgMainRegisterButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        pgMainRegisterButton.setForeground(new java.awt.Color(204, 204, 204));
        pgMainRegisterButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\StartupPage-Register.png")); // NOI18N
        pgMainRegisterButton.setBorder(null);
        pgMainRegisterButton.setBorderPainted(false);
        pgMainRegisterButton.setContentAreaFilled(false);
        pgMainRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgMainRegisterButtonActionPerformed(evt);
            }
        });

        pgMainExitButton.setBackground(new java.awt.Color(0, 100, 172));
        pgMainExitButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        pgMainExitButton.setForeground(new java.awt.Color(204, 204, 204));
        pgMainExitButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\StartupPage-Exit.png")); // NOI18N
        pgMainExitButton.setBorder(null);
        pgMainExitButton.setBorderPainted(false);
        pgMainExitButton.setContentAreaFilled(false);
        pgMainExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgMainExitButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\Startup-Admin.png")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel2.setText("Admin:");

        javax.swing.GroupLayout pgMainPanelLayout = new javax.swing.GroupLayout(pgMainPanel);
        pgMainPanel.setLayout(pgMainPanelLayout);
        pgMainPanelLayout.setHorizontalGroup(
            pgMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgMainPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pgMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pgMainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pgMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pgMainPanelLayout.createSequentialGroup()
                            .addGroup(pgMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pgMainRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pgMainExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pgMainLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pgMainFiller))
                        .addComponent(pgMainTitleLogo)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pgMainPanelLayout.setVerticalGroup(
            pgMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pgMainTitleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(pgMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pgMainPanelLayout.createSequentialGroup()
                        .addComponent(pgMainLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pgMainRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pgMainExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pgMainFiller))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pgMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pgMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pgMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pgMainRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgMainRegisterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgMainRegisterButtonActionPerformed

    private void pgMainLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgMainLoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgMainLoginButtonActionPerformed

    private void pgMainExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgMainExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgMainExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton pgMainExitButton;
    private javax.swing.JTextField pgMainFiller;
    private javax.swing.JButton pgMainLoginButton;
    private javax.swing.JPanel pgMainPanel;
    private javax.swing.JButton pgMainRegisterButton;
    private javax.swing.JLabel pgMainTitleLogo;
    // End of variables declaration//GEN-END:variables
}
