/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a2.tabs.gui.view;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Nathan
 */
public class Dash extends javax.swing.JFrame {

    /**
     * Creates new form Dash
     */
    public Dash() {
        initComponents();
        this.setResizable(false);
        try {UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());} catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException ignored) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        sbTitleButton = new javax.swing.JButton();
        sbHomeButton = new javax.swing.JButton();
        sbSettingsButton = new javax.swing.JButton();
        sbExitButton = new javax.swing.JButton();
        sbProfileButton = new javax.swing.JButton();
        sbMessagesButton = new javax.swing.JButton();
        sbPaymentsButton = new javax.swing.JButton();
        sbHistoryButton = new javax.swing.JButton();
        sbTaxCalculator = new javax.swing.JButton();
        mainProgressBar = new javax.swing.JProgressBar();
        pgMessagesPanel = new javax.swing.JPanel();
        pgMessagesTitle = new javax.swing.JLabel();
        pgMessagesSendMessageHeading = new javax.swing.JLabel();
        pgMessagesSendMessagesTextField = new javax.swing.JTextField();
        pgMessagesSendButton = new javax.swing.JButton();
        pgMessagesMessageHistoryHeading = new javax.swing.JLabel();
        pgMessagesMessageHistoryScroll = new javax.swing.JScrollPane();
        pgMessagesMessageHistoryList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Awesomest Billing System");
        setBackground(new java.awt.Color(51, 51, 51));

        sideBar.setBackground(new java.awt.Color(51, 51, 51));

        sbTitleButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\tabs-logo-dash2.png")); // NOI18N
        sbTitleButton.setBorderPainted(false);
        sbTitleButton.setContentAreaFilled(false);

        sbHomeButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\Menu-Home.png")); // NOI18N
        sbHomeButton.setBorder(null);
        sbHomeButton.setBorderPainted(false);
        sbHomeButton.setContentAreaFilled(false);
        sbHomeButton.setMaximumSize(new java.awt.Dimension(75, 75));
        sbHomeButton.setMinimumSize(new java.awt.Dimension(75, 75));

        sbSettingsButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\Menu-Settings.png")); // NOI18N
        sbSettingsButton.setBorder(null);
        sbSettingsButton.setBorderPainted(false);
        sbSettingsButton.setContentAreaFilled(false);
        sbSettingsButton.setMaximumSize(new java.awt.Dimension(75, 75));
        sbSettingsButton.setMinimumSize(new java.awt.Dimension(75, 75));

        sbExitButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\Menu-Exit.png")); // NOI18N
        sbExitButton.setBorder(null);
        sbExitButton.setBorderPainted(false);
        sbExitButton.setContentAreaFilled(false);
        sbExitButton.setMaximumSize(new java.awt.Dimension(75, 75));
        sbExitButton.setMinimumSize(new java.awt.Dimension(75, 75));
        sbExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbExitButtonActionPerformed(evt);
            }
        });

        sbProfileButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\OptionPane-Profile.png")); // NOI18N
        sbProfileButton.setBorder(null);
        sbProfileButton.setBorderPainted(false);
        sbProfileButton.setContentAreaFilled(false);

        sbMessagesButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\OptionPane-Messages.png")); // NOI18N
        sbMessagesButton.setBorder(null);
        sbMessagesButton.setBorderPainted(false);
        sbMessagesButton.setContentAreaFilled(false);

        sbPaymentsButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\OptionPane-Payments.png")); // NOI18N
        sbPaymentsButton.setBorder(null);
        sbPaymentsButton.setBorderPainted(false);
        sbPaymentsButton.setContentAreaFilled(false);

        sbHistoryButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\OptionPane-History.png")); // NOI18N
        sbHistoryButton.setBorder(null);
        sbHistoryButton.setBorderPainted(false);
        sbHistoryButton.setContentAreaFilled(false);

        sbTaxCalculator.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nathan\\Documents\\Files\\University\\Work\\2022\\Semester-1\\COMP603-12\\A2-TABS-GUI\\resources\\image\\OptionPane-TaxCalculator.png")); // NOI18N
        sbTaxCalculator.setBorder(null);
        sbTaxCalculator.setBorderPainted(false);
        sbTaxCalculator.setContentAreaFilled(false);

        mainProgressBar.setBackground(new java.awt.Color(0, 0, 0));
        mainProgressBar.setForeground(new java.awt.Color(51, 51, 51));
        mainProgressBar.setBorderPainted(false);
        mainProgressBar.setString("50%");

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sbProfileButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sbMessagesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sbPaymentsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sbHistoryButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sbTaxCalculator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sideBarLayout.createSequentialGroup()
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sideBarLayout.createSequentialGroup()
                                .addComponent(sbHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sbSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sbExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sbTitleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sbTitleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sbHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sbSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sbExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sbProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sbMessagesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sbPaymentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sbHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sbTaxCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        pgMessagesPanel.setForeground(new java.awt.Color(246, 247, 251));

        pgMessagesTitle.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        pgMessagesTitle.setForeground(new java.awt.Color(0, 100, 172));
        pgMessagesTitle.setText("Messages");

        pgMessagesSendMessageHeading.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgMessagesSendMessageHeading.setForeground(new java.awt.Color(153, 153, 153));
        pgMessagesSendMessageHeading.setText("Send Message");

        pgMessagesSendMessagesTextField.setBackground(new java.awt.Color(204, 204, 204));
        pgMessagesSendMessagesTextField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgMessagesSendMessagesTextField.setForeground(new java.awt.Color(102, 102, 102));
        pgMessagesSendMessagesTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgMessagesSendMessagesTextField.setCaretColor(new java.awt.Color(102, 102, 102));
        pgMessagesSendMessagesTextField.setOpaque(true);
        pgMessagesSendMessagesTextField.setSelectionColor(new java.awt.Color(252, 189, 27));

        pgMessagesSendButton.setBackground(new java.awt.Color(0, 100, 172));
        pgMessagesSendButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        pgMessagesSendButton.setForeground(new java.awt.Color(204, 204, 204));
        pgMessagesSendButton.setText("Send");
        pgMessagesSendButton.setBorderPainted(false);

        pgMessagesMessageHistoryHeading.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        pgMessagesMessageHistoryHeading.setForeground(new java.awt.Color(153, 153, 153));
        pgMessagesMessageHistoryHeading.setText("Message History");

        pgMessagesMessageHistoryList.setBackground(new java.awt.Color(204, 204, 204));
        pgMessagesMessageHistoryList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));
        pgMessagesMessageHistoryList.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pgMessagesMessageHistoryList.setForeground(new java.awt.Color(102, 102, 102));
        pgMessagesMessageHistoryList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        pgMessagesMessageHistoryList.setSelectionBackground(new java.awt.Color(252, 189, 27));
        pgMessagesMessageHistoryScroll.setViewportView(pgMessagesMessageHistoryList);

        javax.swing.GroupLayout pgMessagesPanelLayout = new javax.swing.GroupLayout(pgMessagesPanel);
        pgMessagesPanel.setLayout(pgMessagesPanelLayout);
        pgMessagesPanelLayout.setHorizontalGroup(
            pgMessagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgMessagesPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pgMessagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pgMessagesMessageHistoryScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pgMessagesMessageHistoryHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pgMessagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pgMessagesTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                        .addComponent(pgMessagesSendMessageHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pgMessagesPanelLayout.createSequentialGroup()
                        .addComponent(pgMessagesSendMessagesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pgMessagesSendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pgMessagesPanelLayout.setVerticalGroup(
            pgMessagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgMessagesPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(pgMessagesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgMessagesSendMessageHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pgMessagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pgMessagesSendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pgMessagesSendMessagesTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pgMessagesMessageHistoryHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgMessagesMessageHistoryScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgMessagesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pgMessagesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sbExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sbExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar mainProgressBar;
    private javax.swing.JLabel pgMessagesMessageHistoryHeading;
    private javax.swing.JList<String> pgMessagesMessageHistoryList;
    private javax.swing.JScrollPane pgMessagesMessageHistoryScroll;
    private javax.swing.JPanel pgMessagesPanel;
    private javax.swing.JButton pgMessagesSendButton;
    private javax.swing.JLabel pgMessagesSendMessageHeading;
    private javax.swing.JTextField pgMessagesSendMessagesTextField;
    private javax.swing.JLabel pgMessagesTitle;
    private javax.swing.JButton sbExitButton;
    private javax.swing.JButton sbHistoryButton;
    private javax.swing.JButton sbHomeButton;
    private javax.swing.JButton sbMessagesButton;
    private javax.swing.JButton sbPaymentsButton;
    private javax.swing.JButton sbProfileButton;
    private javax.swing.JButton sbSettingsButton;
    private javax.swing.JButton sbTaxCalculator;
    private javax.swing.JButton sbTitleButton;
    private javax.swing.JPanel sideBar;
    // End of variables declaration//GEN-END:variables
}
